#!/bin/bash
app_name=burning_clock
tmp_path=/tmp/$app_name
remote_path=/var/www/burning_clock
remote_host=doblock

# Add the necessary ssh key to the ssh-agent if it hasn't been added in this session
# ssh $remote_host "echo 2>&1" || ssh-add ~/.ssh/`echo $app_name`_dsa
ssh $remote_host "echo 2>&1" || ssh-add ~/.ssh/mkzzn_dsa

# Remove the temporary repository if one already exists
[[ -d $tmp_path ]] && rm -rf $tmp_path

# Clone the Git repository to a temporary path
git clone mkzzn_github:mkzzn/$app_name.git $tmp_path

EXCLUDE_ARRAY=(.git)
EXCLUDES=""

for I in ${EXCLUDE_ARRAY[@]}; do
  if test -d $tmp_path/$I; then
    EXCLUDES="${EXCLUDES}--exclude '${tmp_path}/${I}' "
  fi
done

# Sync the temporary repository clone with the remote repository
rsync -avz -e ssh $EXCLUDES $tmp_path $remote_host:$remote_path
